### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by btwGaurav**
Maybe now its working fine

### CODE REVIEW

**Comment by zayn-121** [comment]
Merge ho gaya. Thanks 👍

**Comment by btwGaurav** [comment]
That's great Thank you for merging ///////////////
If you like you can review my project @new-style-coder
It will help me make a stronger portfolio.
Thank you/////////////////
Have a good day!

**Comment by zayn-121** [comment]
Sure.

**Comment by zayn-121** [comment]
Is there any way where I can visit your @new-style-coder

**Comment by btwGaurav** [comment]
Yes, 
first open my profile 
then you can see in top second line overview , repositories , projects
there in projects you can see it.
new-style-coders.

**Comment by zayn-121** [comment]
Muje wo mil gya. Par karna kya hai.
Different columns hain, jisme todo, in progress, done or issue likha aa
raha hai.
Mujhe samajh nahi aa raha hai ki, kya karna hai isme.

**Comment by btwGaurav** [comment]
Its fine I am also unable to find review button so lets forget it and we can do a project together 
tell  me what are the things are you good in
you can also reply on whatsapp .

**Comment by zayn-121** [comment]
Yea sure, I am down. I can create ui using html, css. I am not proficient
with javascript, however I can work my way around it. I also work in
react.js. could you share your WhatsApp?

**Comment by btwGaurav** [comment]
whatsapp = 9755506362

**Pull request merged**
